version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    networks:
      - backend-network
    env_file:
      - .env
      
networks:
  backend-network:
    external: true
