version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://3e8236e757c2bb5bebeef5057ce34918.serveo.net
    ports:
      - "3000:3000"
    networks:
      - backend-network
    env_file:
      - .env
      
networks:
  backend-network:
    external: true
